### ISSUE TITLE
$EDITOR invocation fails if it is not mapped directly to an executable

### ISSUE THREAD

**Issue by LeonardMH** [bbugyi200/localalias#125]
```
System: macOS High Sierra 10.13.2
localalias: 2.6.0 using python 3.7 installed through pip
```
### :shit: Failure
The command `localalias -a cli` fails with the following exception:
```
[ERROR] FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/mvim -v': '/usr/local/bin/mvim -v'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/localalias/app.py", line 31, in main
    _CmdAction.command(args)
  File "/usr/local/lib/python3.7/site-packages/localalias/app.py", line 128, in command
    return cmd()
  File "/usr/local/lib/python3.7/site-packages/localalias/commands.py", line 324, in __call__
    self.edit_alias()
  File "/usr/local/lib/python3.7/site-packages/localalias/commands.py", line 231, in edit_alias
    sp.check_call(editor_cmd_list)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 323, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 304, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/mvim -v': '/usr/local/bin/mvim -v'
Traceback (most recent call last):
  File "/usr/local/bin/localalias", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/localalias/app.py", line 31, in main
    _CmdAction.command(args)
  File "/usr/local/lib/python3.7/site-packages/localalias/app.py", line 128, in command
    return cmd()
  File "/usr/local/lib/python3.7/site-packages/localalias/commands.py", line 324, in __call__
    self.edit_alias()
  File "/usr/local/lib/python3.7/site-packages/localalias/commands.py", line 231, in edit_alias
    sp.check_call(editor_cmd_list)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 323, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 304, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/mvim -v': '/usr/local/bin/mvim -v'
```

### 🔍 Suspected Cause
On my system (and I suspect the system of many macOS users who also use Homebrew MacVim) my `$EDITOR` is set to '/usr/local/bin/mvim -v'. When python attempts to invoke this command it can't find it because it is looking for an actual executable at the path `/usr/local/bin/mvim -v` rather than looking for `/usr/local/bin/mvim` and passing `-v` as the first argument.

### 🚧 Workarounds?
I am able to workaround this issue by setting my editor to /usr/local/bin/vim before calling localalias, such as `EDITOR=/usr/local/bin/vim localalias -a cli`

### ⬆️ Suggested Fix?
The code which opens the editor (at least in the failure from above) is:
```python
if 'EDITOR' in os.environ:
    editor = os.environ['EDITOR']
    log.logger.debug('Editor set to $EDITOR: {}'.format(editor))
else:
    editor = 'vim'
    log.logger.debug('Editor falling back to default: {}'.format(editor))

editor_cmd_list = [editor, tf.name]
try:
    sp.check_call(editor_cmd_list)
except sp.CalledProcessError:
    raise errors.LocalAliasError('Failed to open editor using: {}'.format(editor_cmd_list))
```

This could likely be fixed by changing the code above to use the python [shlex](https://docs.python.org/3.7/library/shlex.html) module (available in all versions of python that you support). Suggested change:

```python
import shlex

try:
    editor_cmd_list = shlex.split(os.environ['EDITOR'])
    log.logger.debug('Editor set to $EDITOR: {}'.format(editor))
except KeyError:
    editor_cmd_list = ['vim']
    log.logger.debug('Editor falling back to default: {}'.format(editor))

editor_cmd_list.append(tf.name)
try:
    sp.check_call(editor_cmd_list)
except sp.CalledProcessError:
    raise errors.LocalAliasError('Failed to open editor using: {}'.format(editor_cmd_list))
```

**Comment by bbugyi200** [comment]
@LeonardMH Thanks for reporting this. Your suggested fix works great (b3ec6c22a7724107149c8982bb5ca3e4508ec0ba). I bumped the version to 2.6.1. You should be able to reinstall to include the patch.
